### ISSUE TITLE
Style of error page

### ISSUE THREAD

**Issue by Smaug6739** [Smaug6739/FGF-site#14]
We need to improve the error page. Currently the page looks like this :
![image](https://user-images.githubusercontent.com/59796136/113508824-823fac80-9552-11eb-98d8-efd0f26a2ca1.png)

But it isn't pretty. Have you idea for improve this page ?

**Comment by SnowTHA** [comment]
Maybe add "Si vous pensez qu'il s'agit d'une erreur, contactez l'administration."
